### ISSUE TITLE
Are wildcard DNS entries required for cloud hosting?

### ISSUE THREAD

**Issue by Susie-in-Ontario** [cloud-gov/cg-site#1139]
hi there
I'm looking for advice and guidance on the issue of wildcard DNS for cloud hosting.
The Government of Ontario is planning an instance with Pivotal Cloud Foundry who insist that this is required.
Among my concerns is the ability to know what's in development, to ensure that it aligns with our needs and meets our standards and all that good stuff
Thanks!
Regards,
Susie Floresco
Manager, Enterprise Web Development (A)
Web Standards and Guidance Coordinator and Domain Registrar
Treasury Board Secretariat
susanne.floresco@ontario.ca
(416) 326-2581
(647) 383-8341

**Comment by pburkholder** [comment]
Hi Susie,

Good to hear from you. Our 18f alumna Hilary Hartley is now over with you folks, right?

I want to make sure to make sure I'm answering the right question. To provide background, for cloud.gov we have a DNS wildcard for *.app.cloud.gov, so any new application, say "newapp", can be accessed at "newapp.app.cloud.gov".

Are you asking: how do we control what's routed to "*.app.cloud.gov" so someone doesn't put a rogue application "myrogueapp.app.cloud.gov"?

Or are you asking somethign else?

If you have access to Slack, I'd recommend bringing this also to the #gov channel in the CloudFoundry community Slack. You can sign up at: https://slack.cloudfoundry.org/

The folks from UK GDS and Australia hang out there too.

Cheers, Peter

**Comment by Susie-in-Ontario** [comment]
hi Peter
Yes, Hillary came north to the Government of Ontario in the spring <happydance>

I am asking about governance and auditability.  A wildcard DNS entry is against our Standard and Guidelines. 

I suppose a different way to ask is what is the route taken to get to the "newapp.app.cloud.gov" spot?  

I'll stay here for now as I'm learning....but I'd very much like the names for gov.uk and the DTA (although I can ask at my next international call as well)

thanks
Susie

**Comment by jmcarp** [comment]
> what is the route taken to get to the "newapp.app.cloud.gov" spot?

When we get a request for some-app.app.cloud.gov, dns resolves to our aws elastic load balancer. The load balancer distributes requests among our cloud foundry routers, which inspect the `Host` http header to figure out which application to route to.

If we didn't use wildcard dns, we'd have to provision a new dns entry for each customer application as soon as it was provisioned. As far as I know, cloud foundry doesn't have that ability, and we'd rather not write custom tooling to do it.

**Comment by pburkholder** [comment]
Hi Susie,

You can still use wildcard DNS and still get the governance control you mentioned.  Here are a few ways.

1. Run a development and a production version of PCF. The development PCF exposes a router with a DNS wildcard for, say *.devapps.ontario.ca, which resolves to an IP address that is _internal only_ to your agency. The production PCF only runs the vetted apps for *.apps.ontario.ca.

2. Run only production PCF. The router would be at *.apps.internal.ontario.ca on an internal only IP address, but then have a load balancer at *.apps.ontario.ca that is configured to route traffic only for the production-approved apps.

3. Have everything open at *.apps.ontario.ca, but configure all the 'organizations' that aren't production-ready have all their apps and services wiped out every 30 days. That would let teams do prototyping, but not tempt them to run anything "for real" since it'll get wiped soon. We have code to enable that if you're interested.

4. There are certainly other ways. If you're paying Pivotal for PCF then they should be able to help you.  If you're not, then just bear in mind: Yes you'd want wildcard DNS for the Cloud Foundry Router IP address to encourage rapid prototyping, but the wildcard DNS doesn't mean you'd have to have everything exposed that's on the IP address.

Cheers, Peter

**Comment by Susie-in-Ontario** [comment]
hmm, i do like the sound of #3, thanks
my main concern is the governance - how do you onboard people to your cloud? how do you ensure that what they tinker with meets a real user need AND your web design standards? i have a legislated need to be able to demonstrate accessibility (and i fear development proceeding merrily along and then receiving the request for prod and hearing 'oh gosh, does it need to be accessible, bilingual, secure and respect privacy?' because the answer is 'yes, yes it does')

thoughts?  
i know a major pain point is the process here for getting a name entered into our DNS zone after approval, this is our internal change management - help me be nimble!

thanks
Susie

**Comment by pburkholder** [comment]
We're a shared-service for various agencies w/in the USGov and we stay out of governance. How they grant access to cloud.gov orgs for their teams is up to them, we usually integrate with their identity providers so when someone leaves an agency, they lose access to cloud.gov w/o any action on our platform; they simply can't authenticate any more.

As for applications, getting authorization for them is also an agency responsibility. Often they tie getting that authorization with getting "official" DNS, so that agencyapp.app.cloud.gov becomes available as agencyapp.agency.gov.

To the larger question, that's a topic that folks write books on. I'd recommend a Lean approach and make an application available as soon as it's accessible, bilingual, secure and respects privacy, even if it's missing most of the intended features, then ensure with a release pipeline that it stays accessible, bilingual, secure, etc as features are added. 

That's a high-level approach, I can recommend books, conferences and videos if you're interested. Cheers, Peter
