### ISSUE TITLE
How does 18F do billing / chargeback for teams running on CF?

### ISSUE THREAD

**Issue by aegershman** [cloud-gov/cg-site#1353]
(Moved from https://github.com/18F/18f.gsa.gov/issues/2895)

I'm very curious how 18f does chargeback for orgs/teams; how is an invoice calculated (e.g., charging for usage based on app/service instance hours), and on how the money is transferred from one org to the platform team (e.g., once a bill has been calculated, how does that money get transferred?):

Some general questions:

- Is it an automated process? Or manually tallied?
- Is there a billing dashboard, similar to how [Pivotal Web Services](https://console.run.pivotal.io) does it's billing?
- Do you integrate with an external billing management system? Or is it built in-house?
- Do you do something with cf-abacus and then manually send out invoices...?

If you can't share, I understand, but I'm very curious about it.

Thank you.

**Comment by aegershman** [comment]
Closing. In case anyone from 18F seeings this: I'd still be very interested in how you do chargeback to clients who run their app workloads on your hosted cloud foundry. Could be a good blog post? :)

**Comment by mogul** [comment]
So sorry we didn't see this earlier! Your last comment made it through the noise. General summary: 

- GSA's TTS sets up interagency agreements with agencies that use cloud.gov. This takes the form of a form 7600A (which establishes the payment channel) and one or more 7600B forms to add on "packages" as described in our [pricing page](https://cloud.gov/pricing/). There's a bit more information on that in [our public handbook page](https://handbook.18f.gov/agreements/#background). Interagency agreements are resolved through the US Treasury, and internal GSA financial accounting ensures that the obligated funds are counted against the cloud.gov "business". 
- When we set up an IAA, there's a funding limit attached. The funding is consumed by monthly packages and usage charges. To align with predictable spend needs from agencies, we currently bill for the CF org quota, rather than individual instance usage. Agencies can raise or lower their quota on request to affect their bill, so long as doing so won't put them above the obligated funds captured in the IAA.
- Because we're billing by quota and changes are rare, we are currently hand-cranking this process.  Our internal accounts-payable group generates invoices for agencies; no external invoicing system "as a service" solutions are cleared for our use. We've discussed automating this whole process but we haven't gone there yet.
- We've also discussed deploying cf-abacus or a similar solution to enable moving to actual instance-usage rather than org quota. It hasn't been a driving need for us or our customers as of yet... Quota charges are a small part of our package fee (which pays for us to keep the platform going), and customers are not optimizing for cost beyond that level yet.
- Because changes in their bill are customer-driven rather than workload-driven, we are not providing a billing dashboard; only changing the org quota causes any differences, and customers know exactly what they'll pay as a result.

Does that help?

**Comment by aegershman** [comment]
It definitely does, thank you for sharing this. I ask because I was looking for chargeback/billing solution ideas for my team to use internally within our company to charge other teams running their apps on our hosted PCF.

- Interesting that customers are charged by quota. I can definitely see how would simplify things, both in terms of calculating the app usage & in terms of billing.
- Do you offer/charge for platform-managed data services, e.g., mysql/redis/rmq/etc.? Or is that included in the quota definition?

Thanks a lot, there aren't many examples of how organizations charge for CF.

**Comment by mogul** [comment]
We aren't currently charging for our managed services because the costs of metering and billing for them outweigh the amount that they cost, and hence would bring in from customers. We are on the lookout for outliers that change that equation, but most of our customers aren't pushing the kind of volume of transactions or storage that make the infra costs worth recouping above and beyond what they're paying via quota (which we know is more than the exact CPU+mem costs of their running apps).

That may change as we bring in managed services that have licensing costs, but again, it's all about when it tips the equation relative to the cost of the effort expended on both sides to reconcile the costs to the invoice (since we're all using taxpayer money... similar to how you and your customers are on the same balance sheet).

If everything were fully automated, then we'd bring down the costs on our side... but it may not actually be a help our customers, who are usually more interested in regular, predictable bills that take them right up to what they budgeted, rather than exact bills.

To some extent, this is us delaying action until the "last responsible moment", eg when this is a top-priority for our customers... Meanwhile there are so many other high-value areas for us to tackle!

**Comment by aegershman** [comment]
Right on, thank you. Yes we're in a similar boat, wherein we're content with "t'll work, good enough" in order to focus on higher priority issues, and basically lightly iterate on it here & there over time until it either 1.) becomes a serious problem requiring a plan, 2.) we have free time to deal with it, or 3.) someone else deals with it, open-sources it, and we try to contribute to it the best we can.

Thanks for sharing this; we're probably going to ~steal~ borrow your team's ideas.

👍

**Comment by mogul** [comment]
You're very welcome!
