### ISSUE TITLE
NFT/ load testing

### ISSUE THREAD

**Issue by RabehTawfik** [cloud-gov/cg-site#1426]
What policies/tools are in place to make sure tenants doing load tests won't affect others or at worst cause denial of service? 

Thanks.

**Comment by mogul** [comment]
See [these Cloud Foundry docs](https://docs.cloudfoundry.org/concepts/container-security.html#mechanics) for specifics about how CPU is apportioned. The algorithm for determining CPU share ensures that no individual app will be DoS'd by a noisy neighbor on the same host.

With reference to the "CPU share is driven by memory limit" point there, each tenant has a specified [organization quota](https://docs.cloudfoundry.org/adminguide/quota-plans.html) that limits their maximum memory usage. cloud.gov's overall deployment is provisioned relative to the total quota amounts of all cloud.gov tenants.

As far as network bandwidth and connections at the edge of the routing tier, etc. we have done load-testing that showed our current capacity is way, _way_ above what all of our customers together typically consume, even accounting for large spikes for particular apps due to heavy publicity, pen-testing, load-testing, etc. We have metrics and alerts that will tell us as platform operators long before we get close to that capacity.

Does this address your concerns?

**Comment by RabehTawfik** [comment]
Yes. many thanks.

**Comment by mogul** [comment]
One note back... We _did_ find just this week that one customer app undergoing an aggressive pen-test with a 16x log-amplification bug (due to having debug settings on in production, and dumping a stack trace on every request) was able to DoS our logging subsystem once the app hit around 350RPS. One of our planned mitigations for future will be to automatically rate-limit requests to apps that spike that high in our routing tier.
