### ISSUE TITLE
Clarify quota units

### ISSUE THREAD

**Issue by jmcarp** [cloud-gov/cg-site#143]
According to https://docs.cloud.gov/apps/quotas/, quotas are allocated in "quota units", each of which provides a fixed number of routes, services, memory, etc. But it's not clear that resources are actually allocated like this--for example, FEC just increased its memory quota by 3GB, which is not a multiple of the 3.75GB quota unit level. As a member of the engineering team and curious reader of the documentation, I don't understand what quota units are, or how or whether they apply to me.

Also, there's a link on this page to https://docs.cloud.gov/apps/quotas/#application-quotas, but the `#application-quotas` anchor doesn't exist on the page, so the link doesn't do anything.

**Comment by mogul** [comment]
(I'd like to take routes out of the equation... They don't cost us anything, so why limit them?)

**Comment by ozzyjohnson** [comment]
In short, "quota units" are a relic of a time when we were not at all clear on the scaling, pricing or rate of oversubscription. They were set that simplify what were then entirely manual processes and getting mired in bespoke quotas and / or running at a loss.

There has been _a lot_ of change since then and units no longer offer the same, if any value.

The work around moving to a continuously deployed CF and usage-based billing should completely outmode this.

@mogul - Same deal with routes, we set route limits at a time when it wasn't clear what the impact of having 10 versus 100 or 1000 routes might be on the routers or how those routers would scale. It might be hard to quantify the cost of a route and that cost might ultimately be negligible, but nothing is free.

**Comment by mogul** [comment]
@dlapiduz and I just discussed this a bit in the weekly grooming session too... It sounds like we want "quota-units" to no longer be a thing, and move to the model where all the usage is charged in terms of MB-used, rather than quota-units-reserved. (That might result in a sudden drop in the actual amount that people are billed... Want to make sure @NoahKunin is aware of that!)

Then the role of the "quota" concept is _only_ as a cap to control spending, for the benefit of the people in charge of the org to limit their exposure, in which case it should also be in units of MB or GB.  Does that sound right? 

Also, it sounds like the way we determine/document the guaranteed CPU for an app will need change... It's based on the memory limit set on each application, but that has been tied to the relative share of quota-unit memory (3.75GB) previously... Is there a straightforward way to derive that now?

**Comment by mogul** [comment]
Actually I take that back:

> rather than quota-units-reserved. (That might result in a sudden drop in the actual amount that people are billed... Want to make sure @NoahKunin is aware of that!)

We never charged in quota-units-reserved, but only ever in terms of quota-units-used. So the amount should be the same... right?

**Comment by mogul** [comment]
Correcting myself as I finally get my head around this... No, it should _still_ result in a drop because people would previously pay in terms of quota-units of 3.75GB, even if they were only using a fraction of one, where now they'd only pay for that fraction of GB actually used. Right?

**Comment by ozzyjohnson** [comment]
> It sounds like we want "quota-units" to no longer be a thing, and move to the model where all the usage is charged in terms of MB-used, rather than quota-units-reserved.

Probably best to drop the "quota unit" idea completely. That was first about capacity planning / billing and second about predictable performance for users. Units haven't been strictly adhered to for a while as anything but a minimum.

> Then the role of the "quota" concept is only as a cap to control spending, for the benefit of the people in charge of the org to limit their exposure, in which case it should also be in units of MB or GB. Does that sound right?

Not exactly. Until there's some form of autoscaling it's also about ensuring availability and limiting exposure as operators as long there's any oversubscription. Users can and have scaled up fast enough to cause contention and starve unrelated orgs of the ability to deploy / scale.

> Also, it sounds like the way we determine/document the guaranteed CPU for an app will need change... It's based on the memory limit set on each application, but that has been tied to the relative share of quota-unit memory (3.75GB) previously... Is there a straightforward way to derive that now?

Guaranteed CPU will stay the same as RAM:CPU is pretty linear across a given instance class, M in this case.

**Comment by ozzyjohnson** [comment]
> Correcting myself as I finally get my head around this... No, it should still result in a drop because people would previously pay in terms of quota-units of 3.75GB, even if they were only using a fraction of one, where now they'd only pay for that fraction of GB actually used. Right?

They've been paying the full price of their quota reserved in MB per day which may or may not be a round multiple of the quota-units we're trying to forget. Moving to a true usage-based model while keeping the same price me MB will cause a drop as most orgs certainly won't have been consuming 100% of their quotas 100% of the time.

**Comment by mogul** [comment]
> > Then the role of the "quota" concept is only as a cap to control spending, for the benefit of the people in charge of the org to limit their exposure, in which case it should also be in units of MB or GB. Does that sound right?
> 
> Not exactly. Until there's some form of autoscaling it's also about ensuring availability and limiting exposure as operators as long there's any oversubscription. Users can and have scaled up fast enough to cause contention and starve unrelated orgs of the ability to deploy / scale.

OK, so we still want to pay attention to the overall quota set across all orgs, and disincentivize setting an arbitrarily high quota per org, since it will drive us to make unwise capacity investments. I'm looking now with `cf quotas` and I can see that we've essentially set up a bespoke CF `quota-plan` for each org.

Quick questions, since [the CF docs](https://docs.cloudfoundry.org/running/managing-cf/quota-plans.html) don't make this clear... 

> Quota plans are not directly associated with user accounts. Instead, every organization has a list of available quota plans, and the account admin assigns a specific quota plan from the list to the organization. Everyone in the organization shares the quotas described by the plan. There is no limit to the number of defined quota plans an account can have, but only one plan can be assigned at a time.
- Does the last usage of "account" there refer to an org, since it said immediately preceding that quota-plans are not associated with user accounts? 
- Only operators can specify new quota-plans and associate them with orgs, right?
- Are `OrgManagers` able to select a new quota-plan for their Org from the list themselves? Or do operators have to select it for them?

I guess I'm trying to figure out how much of this we can make self-service... If:
- only operators can specify new quota-plans and make them available to orgs AND
- OrgManagers can change the selected quota-plan for their org on their own

...then it seems like we should just specify a bunch of generic quota-plans (4G, 8G, 12G, 16G, etc) and make the smaller ones available to all orgs by default. Then there's room for them to go up when they need to and are willing to spend more money, and also a gate on them setting a sky-high quota they'll never use because they'll have to ask us to make a bigger quota-plan available to their org.  Does that sound reasonable?

**Comment by ozzyjohnson** [comment]
> Does the last usage of "account" there refer to an org, since it said immediately preceding that quota-plans are not associated with user accounts?

Yes. However, that paragraph is inconsistent / confusing and best left ignored.

> Only operators can specify new quota-plans and associate them with orgs, right?

Yes.

> Are OrgManagers able to select a new quota-plan for their Org from the list themselves? 

No.

> Or do operators have to select it for them?

Yes, operators have to create and set the org quota plan for them. However, OrgManagers can create, set and manage _space quotas_ within their org.

> I guess I'm trying to figure out how much of this we can make self-service...

None of it.

The only part of this puzzle which currently fits is the concept of generic quotas. A 4GB quota assigned to multiple orgs confers the ability to deploy up to 4GB worth of apps in each org.

Space quotas could possibly be cajoled toward a similar effect by setting a universally "comfortable" org quota and delegating orgmanagers to handle their own space quotas. Beyond that, I'd suggest checking out the API vs CLI to see if what's desired could built into the Deck and / or raising this with Pivotal - space quota delegation was catalyzed by a user request so I'd expect this could be too.

**Comment by mogul** [comment]
> > Are OrgManagers able to select a new quota-plan for their Org from the list themselves?
> 
> No.
> 
> > Or do operators have to select it for them?
> 
> Yes, operators have to create and set the org quota plan for them.

I'm trying to reconcile that with [this Pivotal documentation](https://docs.pivotal.io/pivotalcf/opsguide/change-quota-plan.html) which is nearly as confusing as the community docs, and seems to be in their PCF operator docs. Yet it seems to imply that OrgManagers can in fact set their quota-plan from the list of available plans using `cf curl`. Yet since that documentation was written, the CLI definitely has grown `cf set-quota`, which seems like a more straightforward way to do this. 

I figured I'd try it out, so I made myself an OrgManager for org `sandbox` before trying the following. Granted, I have a privileged account, which makes this a pretty bad test, but it also turned up some weird behavior...

``` bash
# Check current quota definition of org "sandbox" 
 ~  cf curl /v2/organizations/4a962676-e687-46c4-95f4-7a83712065c6 -X 'GET' | grep quota_definition_guid
      "quota_definition_guid": "69736a84-3b19-4a9e-90f0-3e44c3236271",
# The result is the guid for the "sandbox" quota-plan
 ~  cf curl /v2/quota_definitions -X 'GET' | grep -B 8 -A 10 sandbox\"
      {
         "metadata": {
            "guid": "69736a84-3b19-4a9e-90f0-3e44c3236271",
            "url": "/v2/quota_definitions/69736a84-3b19-4a9e-90f0-3e44c3236271",
            "created_at": "2015-10-30T13:36:28Z",
            "updated_at": null
         },
         "entity": {
            "name": "sandbox",
            "non_basic_services_allowed": false,
            "total_services": 1000,
            "total_routes": 1000,
            "total_private_domains": -1,
            "memory_limit": 10240,
            "trial_db_allowed": false,
            "instance_memory_limit": -1,
            "app_instance_limit": -1
         }
      },
# What are the quota details for quota plan "sandbox"?
 ~  cf quotas | grep sandbox
# [...]
sandbox                            10G                  unlimited               1000     1000                disallowed
# What does that quota-plan look like when I ask for the quota for org "sandbox"?
 ~  cf quota sandbox
Getting quota sandbox info as bret.mogilefsky@gsa.gov...
OK

Total Memory         10G
Instance Memory      unlimited
Routes               1000
Services             1000
Paid service plans   disallowed
# OK, so that matches. Let's test if I can set-quota with a different plan (I am an OrgManager)
 ~  cf set-quota sandbox DevOps
Setting quota DevOps to org sandbox as bret.mogilefsky@gsa.gov...
OK
# Succeeded! But did it take?
 ~  cf curl /v2/organizations/4a962676-e687-46c4-95f4-7a83712065c6 -X 'GET' | grep quota_definition_guid
      "quota_definition_guid": "f7963421-c06e-4847-9913-bcd0e6048fa2",
# Yes, the guid changed (to the one associated with quota plan "DevOps")! What are the details of that plan?
 ~  cf curl /v2/quota_definitions -X 'GET' | grep -B 8 -A 10 DevOps
      {
         "metadata": {
            "guid": "f7963421-c06e-4847-9913-bcd0e6048fa2",
            "url": "/v2/quota_definitions/f7963421-c06e-4847-9913-bcd0e6048fa2",
            "created_at": "2015-04-08T18:55:21Z",
            "updated_at": "2015-12-08T21:08:53Z"
         },
         "entity": {
            "name": "DevOps",
            "non_basic_services_allowed": true,
            "total_services": 10000,
            "total_routes": 1000,
            "total_private_domains": -1,
            "memory_limit": 40960,
            "trial_db_allowed": false,
            "instance_memory_limit": -1,
            "app_instance_limit": -1
         }
      },
# OK, so that should match what shows up in 'cf quotas' right?
 ~  cf quotas | grep DevOps
DevOps                             40G                  unlimited               1000     10000               allowed
# Great. So what does the look like for org "sandbox" now that I've set that quota-plan?
 ✘  ~  cf quota sandbox
Getting quota sandbox info as bret.mogilefsky@gsa.gov...
OK

Total Memory         10G
Instance Memory      unlimited
Routes               1000
Services             1000
Paid service plans   disallowed
# Hmmm... So the org's got the quota-plan "DevOps", yet the `cf quota` details are the same as when it had plan "sandbox"?!  Oh well, set it back...
 ~  cf set-quota sandbox sandbox
Setting quota sandbox to org sandbox as bret.mogilefsky@gsa.gov...
OK
```

It seems really weird that I can set a different quota_plan correctly, but get mismatched details from `cf quota`. @ozzyjohnson or @dlapiduz can you explain what's going on here? 

Like I said, this is a bad test for whether OrgManagers can set their own quota plan due to the fact that my main account is not just an OrgManager for "sandbox", but also an operator. I'll try it with my test account tomorrow to eliminate the privileged status from the equation.

**Comment by mogul** [comment]
Never mind, I'm a moron... I thought `cf quota sandbox` was showing me details of the quota for _org_ sandbox. But in reality that's just showing me the details of the _quota plan_ called sandbox. I tried it again, but this time properly using `cf org sandbox` to get the org quota details, and it clearly worked:

```
 ~  cf org sandbox
Getting info for org sandbox as bret.mogilefsky@gsa.gov...
OK

sandbox:
           domains:        apps.cloud.gov
           quota:          sandbox (10240M memory limit, Unlimited instance memory limit, 1000 routes, 1000 services, paid services disallowed)
           spaces:
           space quotas:   1x, 2x, 4x, half, mini, micro, 8x
 ~  cf set-quota sandbox DevOps
Setting quota DevOps to org sandbox as bret.mogilefsky@gsa.gov...
OK
 ~  cf org sandbox
Getting info for org sandbox as bret.mogilefsky@gsa.gov...
OK

sandbox:
           domains:        apps.cloud.gov
           quota:          DevOps (40960M memory limit, Unlimited instance memory limit, 1000 routes, 10000 services, paid services allowed)
           spaces:
           space quotas:   1x, 2x, 4x, half, mini, micro, 8x
 ~  cf set-quota sandbox sandbox
Setting quota sandbox to org sandbox as bret.mogilefsky@gsa.gov...
OK
```

So there's no weird behavior, just me using the wrong command.

Back to the question, whether OrgManagers can change the quota-plan self-service:

```
 ~  cf login -a https://api.cloud.gov -u bret.mogilefsky+1@gsa.gov -o sandbox -s bret.mogilefsky+1
API endpoint: https://api.cloud.gov

Password>
Authenticating...
OK

Targeted org sandbox

Targeted space bret.mogilefsky+1



API endpoint:   https://api.cloud.gov (API version: 2.44.0)
User:           bret.mogilefsky+1@gsa.gov
Org:            sandbox
Space:          bret.mogilefsky+1
 ~  cf org-users sandbox
Getting users in org sandbox as bret.mogilefsky+1@gsa.gov...

ORG MANAGER
  quota-perm-setter
  bret.mogilefsky+1@gsa.gov

BILLING MANAGER
  quota-audit

ORG AUDITOR
  quota-audit
  quota-perm-setter
  monitor-test
 ~  cf set-quota sandbox DevOps
Setting quota DevOps to org sandbox as bret.mogilefsky+1@gsa.gov...
FAILED
Server error, status code: 403, error code: 10003, message: You are not authorized to perform the requested action
```

Darn. :(  It seems kind of ridiculous that admins have to get involved every time someone wants to change their quota-plan... Especially for Pivotal Web Services, which presumably has a heck of a lot more customers than we do. Maybe their web console provides a way for users to change their plan, and uses a privileged user on the back-end to actually make the change? In any case, it sounds like maybe we'd need to do something like that.

By the way, unprivileged users can still see the details of all the quota plans:

```
 ~  cf quotas
Getting quotas as bret.mogilefsky+1@gsa.gov...
OK

name                               total memory limit   instance memory limit   routes   service instances   paid service plans
default                            0                    0                       0        0                   disallowed
FEC-20141001-20150915-01           12G                  unlimited               50       10                  allowed
CAP-20140930-20150930-01           12G                  unlimited               10       10                  disallowed
OCSIT-20141001-20150228-02         7.5G                 unlimited               20       6                   disallowed
BFS-20150101-20190930-01           3.7G                 unlimited               10       3                   disallowed
BFS-20140714-20190717-01           3.7G                 unlimited               10       3                   disallowed
FAS-20140513-20150930-01           15G                  unlimited               20       3                   disallowed
DevOps                             40G                  unlimited               1000     10000               allowed
18F-20150201-20150930-02           1.8G                 unlimited               5        1                   disallowed
OCSIT-20141001-20150930-01         7.5G                 unlimited               20       3                   disallowed
PIF                                7.5G                 unlimited               20       6                   disallowed
ONRR-20140630-20150930-01          3.7G                 unlimited               10       6                   disallowed
ED-20150601-20150930               25G                  unlimited               100      20                  disallowed
DOI-20150519-20160519-PENDING      8G                   unlimited               100      6                   allowed
18F-20150424-20160424-PENDING      7.5G                 unlimited               100      6                   allowed
DOTGOV-20150427-20160427-PENDING   512M                 unlimited               10       6                   disallowed
18F-20150201-20150930-01           3.7G                 unlimited               20       6                   disallowed
federalist-GP                      9.5G                 unlimited               10       20                  disallowed
F4FBGC-0001-0001                   3.7G                 unlimited               10       6                   disallowed
FAS-20150601-20160601-02           3.7G                 unlimited               100      10                  disallowed
CF-ZERO-QUOTA                      1G                   unlimited               0        6                   disallowed
pulse-PENDING                      512M                 unlimited               10       6                   disallowed
epa-PENDING                        1G                   unlimited               10       6                   disallowed
ARY_DJA-15-AEPS-PR-0055            4G                   unlimited               10       6                   allowed
OCSIT-20140904-20150721-03         8G                   unlimited               100      10                  allowed
sandbox-usds                       19.5G                unlimited               1000     0                   disallowed
epa-eenterpriseportal              8G                   unlimited               100      10                  disallowed
epa-emanifest                      8G                   unlimited               100      10                  disallowed
sandbox                            10G                  unlimited               1000     1000                disallowed
gsa-data-gov                       8G                   unlimited               100      20                  disallowed
CATS-persistent-quota              10G                  unlimited               1000     100                 allowed
```

This kind of seems like an information leak in our case, since the list of quotas also telegraphs who the other customers are and how much they're using/spending. So I think there's a good argument for going ahead and making a range of generic plans, replacing those in use with appropriately large ones, and removing the now-deprecated project-specific ones.

**Comment by dlapiduz** [comment]
:+1: to generic quotas

**Comment by mogul** [comment]
/cc @NoahKunin Please confirm that:
1. you're OK with dropping quota-units and just specifying/documenting quota in GB, and 
2. you're OK with replacing the existing per-org quotas with generic quotas. 

I'm not asking so much whether you're OK with it, since I think it's pretty straightforward... Mainly I'm worried about whether there's any unforeseen downstream impact on the billing process if we do this; I don't want to break an existing process when we make the change!

**Comment by mogul** [comment]
@dlapiduz started cleaning this up in 81e17706ca145199ddcdb375656be2fe23baace6

@NoahKunin before we merge that, can you please confirm?

> Mainly I'm worried about whether there's any unforeseen downstream impact on the billing process if we do this; I don't want to break an existing process when we make the change!

**Comment by NoahKunin** [comment]
@mogul I'm ok with all of this. Usage costs are always going to be a very small amount of our revenue. We need consistency and stability in this area, not accuracy at the moment. As long as it doesn't drop revenue more than 5%, we're fine (which per my reading of the above, it won't).

However, _no change can occur_ without the Quotas Billing Portal reflecting this information accurately. So don't PR any documentation change unless that site is going to give accurate information. Please coordinate with @geramirez before merging PRs.

**Comment by mogul** [comment]
We confirmed that the quotas billing portal never knew anything about the quota-unit concept so no technical changes were needed. The text on the page was cleaned up and made accurate as part of #160.
