### ISSUE TITLE
Move the cloud.gov site to Federalist

### ISSUE THREAD

**Issue by eddietejeda** [cloud-gov/cg-site#1500]
Point cloud.gov existing cloudfront URL to the federalist build. https://cg-88d42ca6-59d7-47e0-9500-4dd9251360b9.app.cloud.gov/site/18f/cg-site/

Github branch: https://github.com/18f/cg-site/tree/federalist

## 2020-02-28 acceptance criteria

- [ ] no broken links
- [ ] FedRAMP page is back
- [ ] other keys pages are accounted for (look for 404s in access log)?
- [ ] 404 and other error pages are styled and helpful

**Comment by tammersaleh** [comment]
Hey @eddietejeda - I was wondering if it wouldn't be a better idea for us to use this as a chance to improve the cloud.gov experience.  By moving this to Federalist, we lose a great chance for us to dogfood our own product and learn about end-user pains.

**Comment by siennathesane** [comment]
In a multi-component XaaS business model (which we have), there's a concept of tier or ring services. In each of these tiers or rings are services which are considered fundamental.

In our model, we currently have two rings: 0 and 1. In ring 0, we have the core cloud.gov platform, which is required to do anything. In ring 1, we have Federalist. As the cloud.gov organization grows, we could expand to other services built on top of the core ring 0, similar to Federalist, and they would be considered ring 1 services. If someone wanted to build a dependency on Federalist (i.e. build on top of Federalist, not just use it), it would add another ring, creating ring 2.

In this model, ring 2 is dependent on ring 1 to exist and function, because without it's dependent ring 1 services, it couldn't function. As it exists today, Federalist would cease to function as a ring 1 service if the core cloud.gov services and offerings as a ring 0 service were unavailable.

By taking our public site into Federalist, it takes away our dependency-free ring 0 capabilities and places one of our core dependencies on a ring 1 service, and it no longer dogfoods the core service. In addition, it creates a circular dependency. If cloud.gov goes down, Federalist goes down. Our core site can't come back up until Federalist comes back up, which can't come up until cloud.gov comes up.

I know for a fact this model is used by AWS, GCP, and Azure, and also may be used by others. When I was at AWS Lambda, we were part of the ring 1 service tier, meaning we couldn't come up until EC2 and S3 were up, and were in the process of getting qualified to be a ring 0 service, so we would be part of the core AWS offerings in every region.

If there's a way we can leverage some Federalist functionality for generating the static site with a binary (i.e. some CLI tool), then I'm all for it, but moving our site into Federalist hosting is a _Very Bad Idea<sup>TM</sup>_ because of the potential problems and risk associated with it.

**Comment by eddietejeda** [comment]
This project is complete. We will need to point the cloudfront URL to Federalist build.

**Comment by pburkholder** [comment]
There's a number of things broken with new site, like the 404 page and navigation to FedRAMP info. Reopening this.....
