### ISSUE TITLE
document how to set up new orgs

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#219]
Would be great to have this automated (or single-click/command), but in the meantime, let's create documentation about how to create new sandbox and "production" orgs.

## Acceptance criteria

* [ ] As a cloud.gov admin, I know how to create new organizations in cloud.gov

**Comment by afeld** [comment]
- What information is needed from the requester (`MB #`?)
- Whether @NoahKunin still needs to approve (I hope we can move away from this?)
- What naming conventions are in place

Anything else?

**Comment by dlapiduz** [comment]
I think we need guidance from @NoahKunin on what are the expected steps...

**Comment by afeld** [comment]
Note there may also be a difference for the Prototyping [access package](https://docs.cloud.gov/intro/pricing/rates/#access-package).

https://18f.slack.com/archives/cloud-gov-skyporter/p1472059729000586

**Comment by NoahKunin** [comment]
@afeld I def. don't need to approve anything here. Valid IAAs is where it is at. 
Un-assigning myself!

**Comment by mogul** [comment]
_Apologies for the sloppy formatting below, I don't want to fight with Markdown anymore._

To set up a new organization:

# Create the quota for attributing the organization's usage charges

```
cf create-quota [quotaname] -m [memquota] -r 50 -s 50 --allow-paid-service-plans  
```

Above, `[quotaname]` is:  `[agency]` + _ + `[uniqueBusinessID]` + _ + `[note]`.  The `[uniqueBusinessID]` will direct charges under to this quota to the correct invoice  at billing time. NOTE: [We don't yet have a standard convention for what constitutes a `[uniqueBusinessID]`](https://gsa-tts.slack.com/archives/cloud-gov-business/p1472599576000034); see #cloud-gov-skyporter for help finding one!  
`[memquota]` should be a reasonable initial cap for the systems expected to live in that quota so that clients aren't shocked at their first bill. They can ask for increases as needed.  
Example:  

```
cf create-quota FEC_PR-16-0314_03_prototyping -m 4G -r 50 -s 50 --allow-paid-service-plans  
```

# Create the organization, with usage attributed to the quota we just created

```
cf create-org [orgname] -q [quotaname]  
```

The `[orgname]` should be: `[agency]` + - + `[systemname]`. `[systemname]` should refer to the system for which the access package was purchased. (For prototyping orgs, use `prototyping` as the systemname.)  
Example:  

```
cf create-org fec-prototyping -q FEC_PR-16-0314_03_prototyping  
```

# Create at least one OrgManager in the new organization

```
cf set-org-role [accountname] [orgname] OrgManager  
```

This is the initial owner, who will be able to designate other OrgManagers as needed and add roles for other accounts in the org and the spaces in it.  
Example:  

```
cf set-org-role adrian.webb@gsa.gov fec-prototyping OrgManager  
```

If this fails, ensure that this person already has a cloud.gov account, and send them an invitation if they don't! (For future: We will make it possible to invite a user with roles specified ahead of time in the UI.)

# Inform the OrgManager

Send an e-mail to [accountname] that identifies them as the OrgManager for the new organization and directs them to instructions for setting up spaces, org-roles, space-roles, and space-quotas, and refers them to instructions for getting their org quota raised if needed.

```
<no existing process/template for this right now>  
```

**Comment by mogul** [comment]
(And yes, it goes without saying that this should all be wrapped up in a handy bulletproof script, and thence automated based on a trigger from some other system.)

**Comment by nikzei** [comment]
This is dependent upon whether we agree that our internal docs should be listed in the docs page - see https://github.com/18F/cg-product/issues/346.

**Comment by afeld** [comment]
Worth noting there is now a form for requesting orgs: https://goo.gl/forms/kabLHaza3qp0bg2l2

**Comment by afeld** [comment]
Per @mogul [in Slack](https://gsa-tts.slack.com/archives/cloud-gov/p1478037153002396), the form should be filled out as migrations to GovCloud are done.

/cc @jcscottiii @jezhumble

**Comment by mogul** [comment]
Right, the thought was that we start gathering that data consistently now, even though we're hand-managing the actual org creation as detailed above. Then later if it's just busy-work with few bumps, we can make something that looks at new .csv exports of the sheet attached to that form and makes sure that those orgs/roles/quotas etc. exist.

(The main thing is that the info we're gathering in that form and putting in a clean form into the spreadsheet does not exist in any concise way anywhere else in 18F; it's scattered all over the place. This helps us get it out of random docs and people's heads and into a common reference point.)
