### ISSUE TITLE
Continuous deployment page should recommend best practices for zero-downtime deployment

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#328]
In order to set up great digital services on cloud.gov, cloud.gov users need good instructions for how to set up zero-downtime deployment (blue-green deployment). Currently our [continuous deployment page](https://docs.cloud.gov/apps/continuous-deployment/) has a little bit of info but should have a stronger opinion on what to do and link to appropriate further info.

Reference: [notes from Aidan's training](https://docs.google.com/document/d/1N0VQf5y0ZeO-9BS0Xk1W2p-YetF7HUqzSB4D-Kj7MXw/edit#heading=h.3vjjn2otsjs4).

Basics:
- Be more cautious about recommending `cf-blue-green`
- Provide a little more context
- Link to useful resources
- Link to a good example of an 18F product that is set up to do zero-downtime deployment

**Comment by brittag** [comment]
Noting that @jezhumble knows ~a few things~ about this and offered to help. :)

**Comment by jessieay** [comment]
Some ideas:
-  it seems like `autopilot` is the more popular choice (vs `cf-blue-green`) for zero-downtime deployment (at least that is what we moved to on C2 https://github.com/18F/C2/pull/1112)
- discuss the need to manage environment variables if you are doing a zero-downtime deploy. If all `ENV` vars are defined in your `manifest.yml` file, then you are fine. But if not (and it is likely your case is _not_ because frequently ENV vars are for sensitive keys and you don't want to check those into version control), you need to find a way to let _both_ your app and your second app (that is spun up during zero-downtime deploy) know about `ENV` vars. 
- it seem that the most popular way to deal with env vars is to set them via user-provided services, which are available to all apps in the space in which they are installed. We have some good docs on how we deal with user-provided services and ENV vars for Micropurchase: https://github.com/18F/micropurchase/blob/develop/docs/deployment.md#setting-environment-variables-on-staging-or-production
- right now on Micropurchase we are converting user-provided services into ENV vars via https://github.com/18F/cf-env-parser-buildpack but this is problematic because we can only use that buildpack if we also use https://github.com/ddollar/heroku-buildpack-multi, which is deprecated.
- the solution I am going to look into now is to use this setup https://github.com/18F/acqstackdb/blob/develop/.travis.yml#L26-L33 which takes advantage of https://github.com/18F/18f-cli/blob/develop/scripts/deploy for converting user-provided service instance keys into ENV vars
- this is how C2 manages ENV vars with zero-downtime: https://github.com/18F/C2/blob/master/script/deploy - they just pull ENV vars down into a local `manifest` file that is generated when you run the `deploy` script. So they are not using user-provided services but it's another way of dealing with this problem. (note: the manifest file in this case is gitignored)

**Comment by jessieay** [comment]
Another script for parsing user-provided services and setting them as env vars, via @dlapiduz  https://github.com/18F/discourse/blob/cloud-gov-stage/config/load_cf_env.rb

**Comment by jessieay** [comment]
Update: we tried to use the 18f-cli deploy script and ran into a problem. This method seemed less secure than we had initially thought so we went back to manually parsing user-provided services to retrieve sensitive keys https://github.com/18F/micropurchase/pull/999

**Comment by jessieay** [comment]
One more Pr for dealing with env vars and user-provided services https://github.com/18F/micropurchase/pull/1002

**Comment by afeld** [comment]
It's somewhat tangential, but we need some general best-practices documented, e.g.
- Put as much in [manifest](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html) files as you can
- Put any secrets in [user-provided service instances](https://docs.cloudfoundry.org/devguide/services/user-provided.html)
- Have one space per environment (e.g. `dev`, `staging`, `production`)
  - Each space should look the same in terms of the names of applications, service instances, etc.

**Comment by dogweather** [comment]
Also, I'd like to walk before we run: I'm interested in getting some-downtime deployment working rock-solid.  Then I'll start thinking about zero-downtime.

**Comment by suprenant** [comment]
@mogul is there something you want us to look at here within the Liberator stream?

**Comment by mogul** [comment]
We'd said previously that the Liberator theme included all "self-help facilities", which included user-facing docs and community-based support, but I know that Liberator has become almost exclusively the "web-based UI" team based on the prioritization done to date, and Skyporter didn't exist back then.

Now it does... We're generally expecting Skyporter to take on responsibility for first-tier support (which includes making updates to docs based on the questions that come up) and general community management, which includes polishing docs generated by/with the community and ensuring they get incorporated. 

However, there's definitely a grey area here, at least until we have another content designer on the team who can start chasing things like this down on behalf of both themes... I don't know if @berndverst feels on top of this topic enough yet to make a stab at this one. @berndverst?

**Comment by brittag** [comment]
In the PR at https://github.com/18F/cg-site/pull/1036 I removed the one tiny mention of blue-green deployment because it was part of unmaintained Wercker instructions. We'll need to bring it back in some fashion.

The [production-ready guide has a tiny bit of info about zero-downtime deployment](https://cloud.gov/docs/apps/production-ready/#zero-downtime-deploy) but it's not integrated into the other docs.

**Comment by mogul** [comment]
Closing as stale (and I expect this will get simpler when ZDT commands are finalized in the CF CLI soon).
