### ISSUE TITLE
Drop forks

### ISSUE THREAD

**Issue by jmcarp** [cloud-gov/cg-site#441]
We're currently using personal forks of `onchange` and `anchor-js`. Both forks have slipped behind upstream. If it's important to keep these forks (for example, if we sent pull requests that were rejected upstream), let's move them to the 18F org and pull in upstream. If not, let's switch to upstream.

@msecret

**Comment by msecret** [comment]
The onchange lib is a little tricky because they had a reason for not wanting [our change](https://github.com/msecret/onchange/commit/4b1fe2a6cc2b484bb62bbb10ede0deb0ea514675); including `node_modules` eats too much CPU. But we want the change because we can watch cg-style changes and rebuilt.

That being said, since cg-docs and style aren't being developed in tandem that heavily anymore, it might not be that important to have that functionality.

**Comment by msecret** [comment]
Checked `anchor-js` supposedly it was made npm installable, so we could try using the main package now.

**Comment by afeld** [comment]
> Checked `anchor-js` supposedly it was made npm installable, so we could try using the main package now.

Done in https://github.com/18F/cg-docs/pull/440/commits/20022d307bc64385c96d5b2a7585af2bc1030f16.

**Comment by afeld** [comment]
> The onchange lib is a little tricky

A hack for the current version would be to exclude a single (arbitrary) directory from the CLI...that would prevent `node_modules/` from being excluded. Probably coding to the implementation detail a bit too much though.

https://github.com/Qard/onchange/blob/7a9cf661cfff1567117ad4d0a3dc8a9cfbe38da7/cli.js#L33-L35

**Comment by mogul** [comment]
Closing as stale
