### ISSUE TITLE
Add information about self-hosted continuous deployment tools

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#534]
Question came up in https://gsa-tts.slack.com/archives/g-devops/p1478548389000747. We should include a section about "using Jenkins, Concourse, or some other self-hosted continuous deployment platform?"

https://cloud.gov/docs/apps/continuous-deployment/

**Comment by afeld** [comment]
Would be great to add some information about the brokered Concourse (as an experimental feature). Maybe that's a tangential conversation?

**Comment by mogul** [comment]
Definitely a different conversation. Right now we're not documenting it because we can't offer it to anyone outside of 18F... We need improvements in the isolation between Concourse teams before we'd do that. There's a CI-as-a-Service feature planned and when we take that on we'll reapproach this and hope that either Concourse has gotten better in that regard, that it's straightforward enough we can make the PRs for it, or we have a better option for a CI system to broker that doesn't have this multi-tenancy concern. (Adam seems to like [drone](https://github.com/drone/drone) but I know nothing about it beyond that.) Until then we don't want to get people hyped about it!

**Comment by brittag** [comment]
We have a link to a Jenkins example now, and better overall explanations of setting up CI/CD.
