### ISSUE TITLE
ELB documentation needs updating / deleting

### ISSUE THREAD

**Issue by cnelson** [cloud-gov/cg-site#563]
We either need to update the [ELB Termination](https://cloud.gov/docs/ops/elb/) page with what we do in GovCloud or delete it.

**Acceptance Criteria**
- [ ] ELB documentation is updated or removed form the site

**Comment by cnelson** [comment]
Does any of this information still apply? If not, can we just specifically mention ELBs in the 
the Terraform section in the [aws onboarding](https://cloud.gov/docs/ops/aws-onboarding/) and delete this page?

**Comment by afeld** [comment]
Since the CDN broker is only available in GovCloud (https://cloud.gov/docs/apps/custom-domains/#managed-service-method), seems like it would be sufficient to add a disclaimer to the top of the page with "this only applies to accounts that can't use GovCloud". That being said, maybe we can create the service instances for any new systems that would need it but can't log into GovCloud, and thus we don't need these instructions anymore.

/cc @jmcarp
