### ISSUE TITLE
Make checklist of requirements for making a new cloud.gov repository

### ISSUE THREAD

**Issue by brittag** [cloud-gov/cg-site#592]
In order for the cloud.gov team to follow our own best practices along with our security and compliance requirements, we should have a checklist for making a new cloud.gov repository.

This could be part of our [configuration management plan](https://cloud.gov/docs/ops/configuration-management/), which already includes our GitHub contribution guidelines.

**Examples of what this might include**

* Give it a name starting with `cg` or `cf`
* Add LICENSE, CONTRIBUTING, and README files in compliance with the 18F Open Source Policy
* For repositories with 18F-developed code, set up Code Climate (SI-3)
* Configure a protected master branch with required reviews (CM-9)
* If it's a platform configuration repo, restrict permissions to Cloud Ops
* A continuous integration (CI) server handles automated tests and continuous deployment (CD) of the merged changes (CM plan)

**Acceptance criteria**

- [ ] A cloud.gov docs page provides a helpful checklist for repository requirements.
- [ ] We've notified our team about this (through a `@cloud-gov-team` notification and a team-wide email).

**Comment by brittag** [comment]
Related: https://github.com/18F/development-guide/tree/master/project_setup#initialization-checklist

**Comment by msecret** [comment]
Speaking of `Give it a name starting with cg or cf`, there discussion going on in `cg-dashboard` about how it should technically be renamed to `cf-dashboard` because we're open sourcing it and now other teams using Cloud Foundry are using it. Maybe the guidance should be something like "if the repository is specific to cloud.gov or 18F, it should be named `cg`, otherwise `cf"?
