### ISSUE TITLE
consolidate information about setting up custom domains

### ISSUE THREAD

**Issue by afeld** [cloud-gov/cg-site#679]
* https://cloud.gov/docs/apps/custom-domains/#managed-service-method
* https://cloud.gov/docs/services/cdn-route/

**Comment by brittag** [comment]
We should also figure out whether to rename "CDN service" to "Custom domain service".

**Comment by mogul** [comment]
We shouldn't, because that's not what CDN refers to in this case. Instead, it's [Content Delivery Network](https://en.wikipedia.org/wiki/Content_delivery_network) by virtue of the fact that it's using Cloudfront in the implementation. It just happens to also be a somewhat convenient way to support custom domains, albeit one that [we're considering replacing](https://gsa-tts.slack.com/archives/cloud-gov-atlas/p1483757159003615).

**Comment by brittag** [comment]
Done as part of https://github.com/18F/cg-site/issues/752 !

**Comment by nikzei** [comment]
marked as closed - I'm archiving.
