### ISSUE TITLE
cloud.gov service account documentation does not explain how to obtain username/password

### ISSUE THREAD

**Issue by toolness** [cloud-gov/cg-site#891]
Similar to #864, I noticed today that the documentation for [cloud.gov service account](https://cloud.gov/docs/services/cloud-gov-service-account/) doesn't mention how to obtain the username/password for the created service.

Interestingly, the GitHub repo linked-to from this documentation is the same one linked-to from the docs mentioned in #864. The README on that repo explains how to get the credentials.

Should I submit a PR clarifying this, as I did in #864?  Or should we have a separate page on this credentials broker thing that explains it in one place, and link to it from all the places that reference it?

**Comment by brittag** [comment]
Excellent point, thank you! It sounds good to me to submit a PR clarifying this on this page, very similar to the earlier PR you submitted. It's only a little bit of duplication across two pages, and I believe it best serves the reader's needs to show them this info in context on the page they're already reading, rather than making them switch between multiple pages to get the info they need.

**Comment by toolness** [comment]
Good idea--I will submit a PR soon!
